import React from 'react';
import { Page, Text, View, Document, StyleSheet, Font } from '@react-pdf/renderer';

// Register a standard font (optional, but good for consistency)
// Font.register({ family: 'Roboto', src: 'https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/Roboto-Regular.ttf' });

const styles = StyleSheet.create({
    page: {
        padding: 40,
        fontFamily: 'Helvetica', // Standard PDF font
        fontSize: 12,
        lineHeight: 1.5,
        color: '#333333',
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#aaaaaa',
        paddingBottom: 10,
    },
    title: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 5,
        color: '#111111',
    },
    content: {
        textAlign: 'justify',
    },
    paragraph: {
        marginBottom: 10,
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        textAlign: 'center',
        color: '#888888',
        fontSize: 10,
        borderTopWidth: 1,
        borderTopColor: '#eeeeee',
        paddingTop: 10,
    }
});

interface CoverLetterPdfProps {
    content: string;
}

export const CoverLetterPdf: React.FC<CoverLetterPdfProps> = ({ content }) => {
    // Simple paragraph splitter
    const paragraphs = content.split('\n').filter(p => p.trim().length > 0);

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                <View style={styles.header}>
                    <Text style={styles.title}>Cover Letter</Text>
                </View>
                <View style={styles.content}>
                    {paragraphs.map((para, index) => (
                        <Text key={index} style={styles.paragraph}>
                            {para}
                        </Text>
                    ))}
                </View>
                <View style={styles.footer}>
                    <Text>Generated by ResumeOpti Agent</Text>
                </View>
            </Page>
        </Document>
    );
};
